//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadAwareConfig) DeepCopyInto(out *LoadAwareConfig) {
	*out = *in
	if in.DeschedulingIntervalSeconds != nil {
		in, out := &in.DeschedulingIntervalSeconds, &out.DeschedulingIntervalSeconds
		*out = new(int32)
		**out = **in
	}
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(string)
		**out = **in
	}
	if in.EnablePSIMetrics != nil {
		in, out := &in.EnablePSIMetrics, &out.EnablePSIMetrics
		*out = new(bool)
		**out = **in
	}
	if in.DevDeviationThresholds != nil {
		in, out := &in.DevDeviationThresholds, &out.DevDeviationThresholds
		*out = new(string)
		**out = **in
	}
	if in.EvictionLimitTotal != nil {
		in, out := &in.EvictionLimitTotal, &out.EvictionLimitTotal
		*out = new(int32)
		**out = **in
	}
	if in.EvictionLimitNode != nil {
		in, out := &in.EvictionLimitNode, &out.EvictionLimitNode
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadAwareConfig.
func (in *LoadAwareConfig) DeepCopy() *LoadAwareConfig {
	if in == nil {
		return nil
	}
	out := new(LoadAwareConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectReference) DeepCopyInto(out *ObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectReference.
func (in *ObjectReference) DeepCopy() *ObjectReference {
	if in == nil {
		return nil
	}
	out := new(ObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProfileOptions) DeepCopyInto(out *ProfileOptions) {
	*out = *in
	if in.LoadAware != nil {
		in, out := &in.LoadAware, &out.LoadAware
		*out = new(LoadAwareConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.VirtHigherDensity != nil {
		in, out := &in.VirtHigherDensity, &out.VirtHigherDensity
		*out = new(VirtHigherDensityConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProfileOptions.
func (in *ProfileOptions) DeepCopy() *ProfileOptions {
	if in == nil {
		return nil
	}
	out := new(ProfileOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtHigherDensityConfig) DeepCopyInto(out *VirtHigherDensityConfig) {
	*out = *in
	if in.EnableSwap != nil {
		in, out := &in.EnableSwap, &out.EnableSwap
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtHigherDensityConfig.
func (in *VirtHigherDensityConfig) DeepCopy() *VirtHigherDensityConfig {
	if in == nil {
		return nil
	}
	out := new(VirtHigherDensityConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtPlatformConfig) DeepCopyInto(out *VirtPlatformConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtPlatformConfig.
func (in *VirtPlatformConfig) DeepCopy() *VirtPlatformConfig {
	if in == nil {
		return nil
	}
	out := new(VirtPlatformConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtPlatformConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtPlatformConfigItem) DeepCopyInto(out *VirtPlatformConfigItem) {
	*out = *in
	out.TargetRef = in.TargetRef
	if in.DesiredState != nil {
		in, out := &in.DesiredState, &out.DesiredState
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = (*in).DeepCopy()
	}
	if in.ManagedFields != nil {
		in, out := &in.ManagedFields, &out.ManagedFields
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtPlatformConfigItem.
func (in *VirtPlatformConfigItem) DeepCopy() *VirtPlatformConfigItem {
	if in == nil {
		return nil
	}
	out := new(VirtPlatformConfigItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtPlatformConfigList) DeepCopyInto(out *VirtPlatformConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VirtPlatformConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtPlatformConfigList.
func (in *VirtPlatformConfigList) DeepCopy() *VirtPlatformConfigList {
	if in == nil {
		return nil
	}
	out := new(VirtPlatformConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtPlatformConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtPlatformConfigSpec) DeepCopyInto(out *VirtPlatformConfigSpec) {
	*out = *in
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = new(ProfileOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.WaitTimeout != nil {
		in, out := &in.WaitTimeout, &out.WaitTimeout
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtPlatformConfigSpec.
func (in *VirtPlatformConfigSpec) DeepCopy() *VirtPlatformConfigSpec {
	if in == nil {
		return nil
	}
	out := new(VirtPlatformConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtPlatformConfigStatus) DeepCopyInto(out *VirtPlatformConfigStatus) {
	*out = *in
	if in.AppliedOptions != nil {
		in, out := &in.AppliedOptions, &out.AppliedOptions
		*out = new(ProfileOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VirtPlatformConfigItem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtPlatformConfigStatus.
func (in *VirtPlatformConfigStatus) DeepCopy() *VirtPlatformConfigStatus {
	if in == nil {
		return nil
	}
	out := new(VirtPlatformConfigStatus)
	in.DeepCopyInto(out)
	return out
}
