package plan

import (
	"context"
	"encoding/json"
	"fmt"

	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"sigs.k8s.io/controller-runtime/pkg/client"

	advisorv1alpha1 "github.com/kubevirt/virt-advisor-operator/api/v1alpha1"
)

// ExecuteItem executes a single configuration plan item by applying the stored desired state.
// The desired state is stored in item.DesiredState and contains the complete configuration
// generated by the profile during plan generation.
func ExecuteItem(ctx context.Context, c client.Client, item *advisorv1alpha1.VirtPlatformConfigItem) error {
	// Validate that desired state exists
	if item.DesiredState == nil {
		return fmt.Errorf("plan item missing desired state - this is a bug in plan generation")
	}

	// Convert the stored desired state to an unstructured object
	obj := &unstructured.Unstructured{}
	if err := json.Unmarshal(item.DesiredState.Raw, &obj.Object); err != nil {
		return fmt.Errorf("failed to unmarshal desired state: %w", err)
	}

	// Validate the object has required fields
	if obj.GetKind() == "" || obj.GetAPIVersion() == "" || obj.GetName() == "" {
		return fmt.Errorf("desired state missing required fields (apiVersion, kind, or name)")
	}

	// Use server-side apply with force ownership
	opts := DefaultApplyOptions()
	return ApplyUnstructured(ctx, c, obj, opts)
}
