/*
Copyright 2025 The KubeVirt Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package plan

import (
	"context"
	"encoding/json"
	"fmt"

	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"sigs.k8s.io/controller-runtime/pkg/client"

	advisorv1alpha1 "github.com/kubevirt/virt-advisor-operator/api/v1alpha1"
)

// ExecuteItem executes a single configuration plan item by applying the stored desired state.
// The desired state is stored in item.DesiredState and contains the complete configuration
// generated by the profile during plan generation.
func ExecuteItem(ctx context.Context, c client.Client, item *advisorv1alpha1.VirtPlatformConfigItem) error {
	// Validate that desired state exists
	if item.DesiredState == nil {
		return fmt.Errorf("plan item missing desired state - this is a bug in plan generation")
	}

	// Convert the stored desired state to an unstructured object
	obj := &unstructured.Unstructured{}
	if err := json.Unmarshal(item.DesiredState.Raw, &obj.Object); err != nil {
		return fmt.Errorf("failed to unmarshal desired state: %w", err)
	}

	// Validate the object has required fields
	if obj.GetKind() == "" || obj.GetAPIVersion() == "" || obj.GetName() == "" {
		return fmt.Errorf("desired state missing required fields (apiVersion, kind, or name)")
	}

	// Use server-side apply with force ownership
	opts := DefaultApplyOptions()
	return ApplyUnstructured(ctx, c, obj, opts)
}
